//Author:tonacoin
//@version=3
strategy("HMA+CCI strategy v0.1", overlay=true)

src = input(close)
hmaLen = input(21, "HMA Length")
cciLen = input(10, "CCI Length")
cciLower = input(-50, "CCI Lower Limit")
cciUpper = input(50, "CCI Upper Limit")
cciLowerExit = input(-100, "CCI Lower Exit")
cciUpperExit = input(100, "CCI Upper Exit")
hmaExit = input(false, "Use HMA for Exit?")
cciExit = input(true, "Use CCI for Exit?")

// Backtest
fromyear = input(2017, defval = 2018, minval = 1900, maxval = 2100, title = "From Year")
toyear = input(2100, defval = 2100, minval = 1900, maxval = 2100, title = "To Year")
frommonth = input(01, defval = 01, minval = 01, maxval = 12, title = "From Month")
tomonth = input(12, defval = 12, minval = 01, maxval = 12, title = "To Month")
fromday = input(21, defval = 01, minval = 01, maxval = 31, title = "From day")
today = input(31, defval = 31, minval = 01, maxval = 31, title = "To day")

leverage = input(100, "Leverage")

term = (time > timestamp(fromyear, frommonth, fromday, 00, 00) and time < timestamp(toyear, tomonth, today, 23, 59))

hullma = wma(2*wma(src, hmaLen/2)-wma(src, hmaLen), round(sqrt(hmaLen)))
cci = cci(close, cciLen)
plot(hullma, color=hullma[1]>hullma?red:green, linewidth=4)
longCondition = hullma[1] < hullma and crossover(cci, cciLower)
shortCondition = hullma[1] > hullma and crossunder(cci, cciUpper)
exitLong1 = hmaExit ? hullma[1] > hullma : false
exitLong2 = cciExit ? cci > cciUpperExit : false
exitShort1 = hmaExit ? hullma[1] < hullma : false
exitShort2 = cciExit ? cci < cciLowerExit : false

if (longCondition and term)
    strategy.entry("Long",  strategy.long, qty=strategy.initial_capital/close*leverage)
if (shortCondition and term)
    strategy.entry("Short",  strategy.short, qty=strategy.initial_capital/close*leverage)
        
if strategy.position_size > 0 and term
    if (exitLong1 or exitLong2)
        strategy.close_all()
        
if strategy.position_size < 0 and term
    if (exitShort1 or exitShort2)
        strategy.close_all()